[dependencies]
base = "0.10.2"
candb = "https://github.com/vporton/CanDB#no-blob"
nacdb = "https://github.com/vporton/NacDB#main"
stable-rbtree = "1.0.0"
stable-buffer = "https://github.com/canscale/StableBuffer#v0.2.0"
stablebuffer = "https://github.com/canscale/StableBuffer#v0.2.0"
StableBuffer = "https://github.com/canscale/StableBuffer#v0.2.0"
icrc1 = "0.0.2"
itertools = "0.1.2"
StableTrieMap = "https://github.com/NatLabs/StableTrieMap#main"
array = "https://github.com/aviate-labs/array.mo#main"
xtendedNumbers = "https://github.com/edjCase/motoko_numbers#v1.1.0"
motoko-lib = "https://github.com/research-ag/motoko-lib#0.7"
map7 = "https://github.com/ZhenyaUsenko/motoko-hash-map#v7.0.0"
sha = "https://github.com/enzoh/motoko-sha#master"
stableheapbtreemap = "1.3.0"
map = "9.0.1"
btree = "https://github.com/canscale/StableHeapBTreeMap#v0.3.3"
CanDBMulti = "https://github.com/vporton/CanDBMulti#v0.10.0@86d00711216349ba4879370d6313d44a26d16f61"
xtended-numbers = "0.2.1"
NacDBReorder = "https://github.com/vporton/NacDBReorder#v2.0.0@44dda638900a372c93f21a6d1ae76ef84e86b1e5"
passport-client-dfinity = "https://github.com/vporton/passport-client-dfinity#master@ae1cce82128cdfd90bb46e3a462134e6666bc456"

[dev-dependencies]
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.0"
