[dependencies]
base = "0.10.2"
matchers = "https://github.com/kritzcreek/motoko-matchers#3dac8a071b69e4e651b25a7d9683fe831eb7cffd"
candb = "https://github.com/vporton/CanDB#no-blob"
nacdb = "https://github.com/vporton/NacDB#main"
reorder = "https://github.com/vporton/NacDBReorder#main"
stable-rbtree = "https://github.com/canscale/StableRBTree#v0.6.1"
btree = "https://github.com/canscale/StableHeapBTreeMap#v0.3.1"
stable-buffer = "https://github.com/canscale/StableBuffer#v0.2.0"
stablebuffer = "https://github.com/canscale/StableBuffer#v0.2.0"
StableBuffer = "https://github.com/canscale/StableBuffer#v0.2.0"
icrc1 = "0.0.2"
itertools = "https://github.com/NatLabs/itertools#main"
StableTrieMap = "https://github.com/NatLabs/StableTrieMap#main"
array = "https://github.com/aviate-labs/array.mo#v0.2.1"
xtendedNumbers = "https://github.com/edjCase/motoko_numbers#v1.1.0"
motoko-lib = "https://github.com/research-ag/motoko-lib#0.7"
map7 = "https://github.com/ZhenyaUsenko/motoko-hash-map#v7.0.0"
sha = "https://github.com/enzoh/motoko-sha#master"
candy = "https://github.com/icdevs/candy_library#0.2.0"
